name: Publish Unity Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu_x64_cmd
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@Spatial-Realities-Group' # Defaults to the user or organization that owns the workflow file
    - run: npm publish
      working-directory: PackageTesting/Packages/com.spatial-realities.test
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
