name: Publish Unity Package
on:
  workflow_dispatch:
    inputs:
      working_directory:
        type: string
        required: true
        description: 'A relative path that starts from the repo root to the folder containing the packages package.json file'
      organization:
        type: string
        required: false
        description: 'Change this if the organization or user that the package is published against is different'
        default: '@octocat' # Defaults to the user or organization that owns the workflow file
jobs:
  call_publish_unity_package:
    uses: ./.github/workflows/publish_unity_package.yml
    with:
      working_directory: ${{ inputs.working_directory }}
    permissions:
      contents: read
      packages: write
