name: Publish Unity Package
on:
  workflow_dispatch:
    inputs:
      version_source:
        description: 'Which source will be used to determine this packages version'
        type: choice
        required: true
        default: "PackageJson"
        options:
          - PackageJson
          - GitTag
jobs:
  call_publish_unity_package:
    uses: ./.github/workflows/upload_unity_package.yml
    permissions:
      contents: read
      packages: write
