name: Upload Unity Package
on:
  workflow_call:
jobs:
  npm_registery_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Create Abs Package Path
      run : echo "PACKAGE_PATH=${{ github.workspace }}/${{ vars.PACKAGE_ROOT_PATH }}/package.json" >> $GITHUB_ENV
    - name: Get Version (PackageJson)
      if: ${{ inputs.version_source }} == 'PackageJson'
      run: python .github/workflows/getUnityPackageVersion.py "${{ env.PACKAGE_PATH }}" "GITHUB_ENV"
    - name: Get Version (GitTag)
      if: ${{ inputs.version_source }} == 'GitTag'
      run: echo "PACKAGE_VERSION=1.0.9" >> $GITHUB_ENV
    - name: Get Version (Manual)
      if: ${{ inputs.version_source }} == 'Manual'
      run: echo "PACKAGE_VERSION=1.11.0" >> $GITHUB_ENV
    - name: Print Version
      run: echo "${{ env.PACKAGE_VERSION }}"
    # Setup .npmrc file to publish to GitHub Packages
    # - uses: actions/setup-node@v1
      # with:
        # node-version: '12.x'
        # registry-url: 'https://npm.pkg.github.com'
        # scope: '@octocat' # Defaults to the user or organization that owns the workflow file
    # - run: npm publish
      # working-directory: ${{ inputs.working_directory }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
